name: Tool Versions Update Action - Pull Request
description: Update tools in your .tool-versions file through a Pull Request
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  assignees:
    description: |
      A comma or newline-separated list of assignees for the Pull Request (by
      their GitHub username).
    required: false
    default: ""
  commit-message:
    description: |
      The message to use for update commits.
    required: false
    default: Update .tool-versions
  labels:
    description: |
      A comma or newline-separated list of labels.
    required: false
    default: ""
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  only:
    description: |
      A comma-separated list of tools that should be updated, ignoring others.
    required: false
    default: ""
  plugins:
    description: |
      A list of newline-separated "plugin url" pairs that should be installed.
      If omitted the default plugins will be available.
    required: false
    default: ""
  pr-base:
    description: |
      The base branch to use for Pull Requests.
    required: false
    default: ${{ github.head_ref }}
  pr-body:
    description: |
      The body text to use for Pull Requests.
    required: false
    default: Bump tools in `.tool-versions`
  pr-title:
    description: |
      The title to use for Pull Requests.
    required: false
    default: Update `.tool-versions`
  reviewers:
    description: |
      A comma or newline-separated list of reviewers for the Pull Request (by
      their GitHub username).
    required: false
    default: ""
  token:
    description: |
      The $GITHUB_TOKEN or a repository scoped Personal Access Token (PAT).
    required: false
    default: ${{ github.token }}

outputs:
  commit-sha:
    description: The SHA identifier of the created commit.
    value: ${{ steps.create-pr.outputs.pull-request-head-sha }}
  did-update:
    description: true if at least one tool was updated, false otherwise.
    value: ${{ steps.update.outputs.did-update }}
  pr-number:
    description: The number of the created Pull Request.
    value: ${{ steps.create-pr.outputs.pull-request-number }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3

    - name: Setup asdf
      if: ${{ inputs.plugins != '' }}
      uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # pin@v2
    - name: Configure asdf plugins
      if: ${{ inputs.plugins != '' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/install-plugins.sh
      env:
        LIST: ${{ inputs.plugins }}

    - name: Install asdf
      uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4 # pin@v2

    - name: Look for updates
      id: update
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}
        ONLY: ${{ inputs.only }}

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # pin@v5
      with:
        token: ${{ inputs.token }}

        # Pull Request
        title: ${{ inputs.pr-title }}
        body: ${{ inputs.pr-body }}
        base: ${{ inputs.pr-base }}
        reviewers: ${{ inputs.reviewers }}
        assignees: ${{ inputs.assignees }}
        labels: ${{ inputs.labels }}

        # Branch
        branch: tool-versions-updates

        # Commit
        commit-message: ${{ inputs.commit-message }}
        add-paths: .tool-versions
