name: Tool Versions Update Action - Pull Request
description: Update tools in your .tool-versions file through a Pull Request
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  labels:
    description: |
      A comma or newline-separated list of labels.
    required: false
    default: ""
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  plugins:
    description: |
      A list of newline-separated "plugin url" pairs that should be installed.
      If omitted the default plugins will be available.
    required: false
    default: ""
  token:
    description: |
      The $GITHUB_TOKEN or a repository scoped Personal Access Token (PAT).
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup asdf
      if: ${{ inputs.plugins != '' }}
      uses: asdf-vm/actions/setup@v2
    - name: Configure asdf plugins
      if: ${{ inputs.plugins != '' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/install-plugins.sh
      env:
        LIST: ${{ inputs.plugins }}

    - name: Install asdf
      uses: asdf-vm/actions/install@v2

    - name: Look for updates
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.token }}

        # Pull Request
        title: Update `.tool-versions`
        body: Bump tools in `.tool-versions`
        labels: ${{ inputs.labels }}

        # Branch
        branch: tool-versions-updates

        # Commit
        commit-message: Update .tool-versions
        add-paths: .tool-versions
