name: Tool Versions Update Action
description: Update tools in your .tool-versions file
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  only:
    description: |
      A comma-separated list of tools that should be updated, ignoring others.
    required: false
    default: ""
  skip:
    description: |
      A newline-separated list of "tool version" pairs that should NOT be
      updated to.
    required: false
    default: ""

outputs:
  did-update:
    description: true if at least one tool was updated, false otherwise.
    value: ${{ steps.update.outputs.updated-count != '0' }}
  updated-count:
    description: The number of tools that were updated.
    value: ${{ steps.update.outputs.updated-count }}
  updated-new-versions:
    description: A comma separated list of the new versions of updated tools.
    value: ${{ steps.update.outputs.new-versions }}
  updated-old-versions:
    description: A comma separated list of the old versions of updated tools.
    value: ${{ steps.update.outputs.old-versions }}
  updated-tools:
    description: A comma separated list of the names of the updated tools.
    value: ${{ steps.update.outputs.updated-tools }}
  updated-tools-json:
    description: A JSON array of objects containing the name, old and new version of updated tools.
    value: ${{ steps.update.outputs.updated-tools-json }}
  updated-tools-table:
    description: A markdown table showing the tool names with their old and new versions.
    value: ${{ steps.update.outputs.updated-tools-table }}

runs:
  using: composite
  steps:
    - name: Look for updates
      id: update
      shell: bash
      run: $GITHUB_ACTION_PATH/bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}
        ONLY: ${{ inputs.only }}
        SKIP: ${{ inputs.skip }}
