name: Tool Versions Update Action
description: Update tools in your .tool-versions file
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  only:
    description: |
      A comma-separated list of tools that should be updated, ignoring others.
    required: false
    default: ""

outputs:
  did-update:
    description: true if at least one tool was updated, false otherwise.
    value: ${{ steps.update.outputs.did-update }}
  updated-count:
    description: The number of tools that were updated.
    value: ${{ steps.update.outputs.updated-count }}

runs:
  using: composite
  steps:
    - name: Look for updates
      id: update
      shell: bash
      run: $GITHUB_ACTION_PATH/bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}
        ONLY: ${{ inputs.only }}
