# SPDX-License-Identifier: MIT-0

# Check out Docker at: https://www.docker.com/
# Check out Podman at: https://podman.io/

FROM docker.io/alpine:3.19.1

RUN apk add --no-cache \
	bash curl git jq make python3 py3-pip

ENV ASDF_DIR="/.asdf"

WORKDIR /setup
COPY .tool-versions .

RUN git clone https://github.com/asdf-vm/asdf.git /.asdf --branch v0.14.0 \
	&& echo '. "/.asdf/asdf.sh"' > ~/.bashrc \
	&& . '/.asdf/asdf.sh' \
	&& asdf plugin add actionlint \
	&& asdf plugin add hadolint \
	&& asdf plugin add shellcheck \
	&& asdf plugin add shellspec \
	&& asdf plugin add shfmt \
	&& asdf plugin add yamllint \
	&& asdf install

ENTRYPOINT ["/bin/bash"]
