# SPDX-License-Identifier: MIT-0

FROM docker.io/golang:1.25.0-alpine3.21

RUN apk add --no-cache \
	bash curl git jq make python3 py3-pip \
	&& \
	git config --global --add safe.directory /tool-versions-update-action

ENV ASDF_DATA_DIR="/.asdf"

WORKDIR /setup
COPY .tool-versions .

RUN go install github.com/asdf-vm/asdf/cmd/asdf@v0.16.2 \
	&& echo 'export PATH="/.asdf/shims:$''PATH"' > ~/.bashrc \
	&& asdf plugin add actionlint \
	&& asdf plugin add hadolint \
	&& asdf plugin add shellcheck \
	&& asdf plugin add shellspec \
	&& asdf plugin add shfmt \
	&& asdf plugin add yamllint \
	&& asdf install

ENTRYPOINT ["/bin/bash"]
