name: Tool Versions Update Action - commit
description: Update tools in your .tool-versions file through a commit
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  branch:
    description: |
      The branch to commit to.
    required: false
    default: ${{ github.head_ref }}
  commit-message:
    description: |
      The message to use for commits.
    required: false
    default: Update .tool-versions
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  only:
    description: |
      A comma-separated list of tools that should be updated, ignoring others.
    required: false
    default: ""
  plugins:
    description: |
      A newline-separated list of "plugin url" pairs that should be installed.
      If omitted the default plugins will be available.
    required: false
    default: ""
  token:
    description: |
      The $GITHUB_TOKEN or a repository scoped Personal Access Token (PAT).
    required: false
    default: ${{ github.token }}

outputs:
  commit-sha:
    description: The SHA identifier of the created commit.
    value: ${{ steps.create-commit.outputs.commit_hash }}
  did-update:
    description: true if at least one tool was updated, false otherwise.
    value: ${{ steps.update.outputs.did-update }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ inputs.token }}

    - name: Setup asdf
      if: ${{ inputs.plugins != '' }}
      uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # pin@v3
    - name: Configure asdf plugins
      if: ${{ inputs.plugins != '' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/install-plugins.sh
      env:
        LIST: ${{ inputs.plugins }}

    - name: Install asdf
      uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # pin@v3

    - name: Look for updates
      id: update
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}
        ONLY: ${{ inputs.only }}

    - name: Create commit
      id: create-commit
      uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # pin@v5
      with:
        skip_dirty_check: false

        # Branch
        branch: ${{ inputs.branch }}

        # Commit
        commit_message: ${{ inputs.commit-message }}
        file_pattern: .tool-versions
