name: Tool Versions Update Action - commit
description: Update tools in your .tool-versions file through a commit
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  branch:
    description: |
      The branch to commit to.
    required: false
    default: ${{ github.head_ref }}
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  only:
    description: |
      A comma-separated list of tools that should be updated, ignoring others.
    required: false
    default: ""
  plugins:
    description: |
      A list of newline-separated "plugin url" pairs that should be installed.
      If omitted the default plugins will be available.
    required: false
    default: ""
  token:
    description: |
      The $GITHUB_TOKEN or a repository scoped Personal Access Token (PAT).
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ inputs.token }}

    - name: Setup asdf
      if: ${{ inputs.plugins != '' }}
      uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # pin@v2
    - name: Configure asdf plugins
      if: ${{ inputs.plugins != '' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/install-plugins.sh
      env:
        LIST: ${{ inputs.plugins }}

    - name: Install asdf
      uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4 # pin@v2

    - name: Look for updates
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}
        ONLY: ${{ inputs.only }}

    - name: Create commit
      uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # pin@v4
      with:
        skip_dirty_check: false

        # Branch
        branch: ${{ inputs.branch }}

        # Commit
        commit_message: Update `.tool-versions`
