name: Tool Versions Update Action - commit
description: Update tools in your .tool-versions file through a commit
branding:
  icon: arrow-up-circle
  color: blue

inputs:
  branch:
    description: |
      The branch to commit to.
    required: false
    default: ${{ github.head_ref }}
  commit-message:
    description: |
      The message to use for commits.
    required: false
    default: |
      Update {{updated-tools}}

      Update {{updated-count}} tool(s): {{updated-tools}}
      - Version(s) before: {{updated-old-versions}}
      - Version(s) after:  {{updated-new-versions}}
  max:
    description: |
      The maximum number of tools to update. 0 indicates no maximum.
    required: false
    default: 0
  not:
    description: |
      A comma-separated list of tools that should NOT be updated.
    required: false
    default: ""
  only:
    description: |
      A comma-separated list of tools that should be updated, ignoring others.
    required: false
    default: ""
  plugins:
    description: |
      A newline-separated list of "plugin url" pairs that should be installed.
      If omitted the default plugins will be available.
    required: false
    default: ""
  signoff:
    description: |
      Add "Signed-off-by" line at the end of the commit message. See `--signoff`
      in <https://git-scm.com/docs/git-commit> for more detail.
    required: false
    default: false
  skip:
    description: |
      A newline-separated list of "tool version" pairs that should NOT be
      updated to.
    required: false
    default: ""
  token:
    description: |
      The $GITHUB_TOKEN or a repository scoped Personal Access Token (PAT).
    required: false
    default: ${{ github.token }}

outputs:
  commit-sha:
    description: The SHA identifier of the created commit.
    value: ${{ steps.create-commit.outputs.commit_hash }}
  did-update:
    description: true if at least one tool was updated, false otherwise.
    value: ${{ steps.update.outputs.updated-count != '0' }}
  updated-count:
    description: The number of tools that were updated.
    value: ${{ steps.update.outputs.updated-count }}
  updated-new-versions:
    description: A comma separated list of the new versions of updated tools.
    value: ${{ steps.update.outputs.new-versions }}
  updated-old-versions:
    description: A comma separated list of the old versions of updated tools.
    value: ${{ steps.update.outputs.old-versions }}
  updated-tools:
    description: A comma separated list of the names of the updated tools.
    value: ${{ steps.update.outputs.updated-tools }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5
      with:
        token: ${{ inputs.token }}
        persist-credentials: true

    - name: Setup asdf
      if: ${{ inputs.plugins != '' }}
      uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # pin@v3
    - name: Configure asdf plugins
      if: ${{ inputs.plugins != '' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/install-plugins.sh
      env:
        LIST: ${{ inputs.plugins }}

    - name: Install asdf
      uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # pin@v3

    - name: Look for updates
      id: update
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/update.sh
      env:
        MAX: ${{ inputs.max }}
        NOT: ${{ inputs.not }}
        ONLY: ${{ inputs.only }}
        SKIP: ${{ inputs.skip }}

    - name: Commit message
      id: commit-message
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/templating.sh
      env:
        TEXT: ${{ inputs.commit-message }}
        UPDATED_COUNT: ${{ steps.update.outputs.updated-count }}
        UPDATED_NEW_VERSIONS: ${{ steps.update.outputs.updated-new-versions }}
        UPDATED_OLD_VERSIONS: ${{ steps.update.outputs.updated-old-versions }}
        UPDATED_TOOLS: ${{ steps.update.outputs.updated-tools }}
    - name: Branch name
      id: branch
      shell: bash
      run: $GITHUB_ACTION_PATH/../bin/templating.sh
      env:
        TEXT: ${{ inputs.branch }}
        UPDATED_COUNT: ${{ steps.update.outputs.updated-count }}
        UPDATED_NEW_VERSIONS: ${{ steps.update.outputs.updated-new-versions }}
        UPDATED_OLD_VERSIONS: ${{ steps.update.outputs.updated-old-versions }}
        UPDATED_TOOLS: ${{ steps.update.outputs.updated-tools }}

    - name: Commit options
      id: commit-options
      shell: bash
      run: |
        if [[ "${SIGNOFF}" == 'true' ]]; then
          echo "value=--signoff" >>"${GITHUB_OUTPUT}"
        fi
      env:
        SIGNOFF: ${{ inputs.signoff }}

    - name: Create commit
      if: ${{ steps.update.outputs.updated-count != '0' }}
      id: create-commit
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # pin@v6
      with:
        skip_dirty_check: false

        # Branch
        branch: ${{ steps.branch.outputs.value }}

        # Commit
        commit_message: ${{ steps.commit-message.outputs.value }}
        commit_options: ${{ steps.commit-options.outputs.value }}
        file_pattern: .tool-versions
