name: Secrets
on:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: 0 1 * * *

permissions: read-all

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@735bac03911974e37641f570a5582a9b72f49a44 # v3.84.0
        with:
          extra_args: --only-verified
