name: Secrets
on:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: 0 1 * * *

permissions: read-all

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@0328a19a9d3877c9f04d0dbee5717aabff5b575d # v3.82.6
        with:
          extra_args: --only-verified
