name: Transitive Actions
on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch: ~

permissions: read-all

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Create token to create Pull Request
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: automation-token
        with:
          client-id: ${{ secrets.AUTOMATION_ID }}
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
      - name: Update (and pin) all actions used by these actions
        run: make update-actions
        env:
          GH_ADMIN_TOKEN: ${{ github.token }}
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ steps.automation-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          if git diff --quiet 'commit/action.yml' 'pr/action.yml' 'action.yml'; then
            echo 'No changes.'
            exit 0
          fi

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -B 'action-deps-update'
          git add 'commit/action.yml' 'pr/action.yml' 'action.yml'
          git commit --message 'Update composite action dependencies'

          git remote set-url 'origin' "https://x-access-token:${GH_TOKEN}@github.com/${REPOSITORY}"
          git push --force 'origin' 'action-deps-update'

          gh pr create \
            --base='main' --head='action-deps-update' \
            --label='dependencies' \
            --title='Update composite action dependencies' \
            --body='_This Pull Request was automatically generated by `transitive-actions.yml`_

          ---

          Bump the versions of dependencies used in composite action to the latest available version.

          If any dependency was not previously pinned, it should be pinned now.

          Please update the `CHANGELOG.md` in accordance with these changes before you merge this.'
